openapi: 3.0.3
info:
  title: Vinta Boilerplate API
  version: 0.1.0
  description: A Django project boilerplate with Vinta's best practices
paths:
  /api/chat/chat/:
    post:
      operationId: chat_chat_create
      description: Sends a new message and previous history to Gemini, returning the
        model's response and the updated history.
      summary: Gemini Chat Conversation Turn
      tags:
      - chat
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            examples:
              ChatRequestExample:
                value:
                  prompt: Hva er hovedprinsippene i norsk personvernslovgivning?
                  history:
                  - role: user
                    parts:
                    - text: Forrige spørsmål
                  - role: model
                    parts:
                    - text: Forrige svar
                  context_text: Valgfri kontekst for RAG
                  system_instructions: Svar som en juridisk ekspert
                  model_name: gemini-2.5-flash
                summary: Chat Request Example
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChatRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChatRequest'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
          description: ''
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
          description: ''
  /api/counter/increment/:
    post:
      operationId: counter_increment_create
      tags:
      - counter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Counter'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Counter'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Counter'
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Counter'
          description: ''
  /api/rest/rest-check/:
    get:
      operationId: rest_rest_check_retrieve
      description: This endpoint checks if the REST API is working.
      summary: Check REST API
      tags:
      - rest
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples:
                SuccessfulResponse:
                  value:
                    message: This message comes from the backend. If you're seeing
                      this, the REST API is working!
                  summary: Successful Response
          description: ''
  /api/test-response/:
    get:
      operationId: test_response_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - test-response
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMockResponseList'
          description: ''
    post:
      operationId: test_response_create
      tags:
      - test-response
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MockResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MockResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MockResponse'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
          description: ''
  /api/test-response/{id}/:
    get:
      operationId: test_response_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mock response.
        required: true
      tags:
      - test-response
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
          description: ''
    put:
      operationId: test_response_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mock response.
        required: true
      tags:
      - test-response
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MockResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MockResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MockResponse'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
          description: ''
    patch:
      operationId: test_response_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mock response.
        required: true
      tags:
      - test-response
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMockResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMockResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMockResponse'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
          description: ''
    delete:
      operationId: test_response_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mock response.
        required: true
      tags:
      - test-response
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/test-response/fetch_by_keyword/:
    post:
      operationId: test_response_fetch_by_keyword_create
      tags:
      - test-response
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MockResponse'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MockResponse'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MockResponse'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MockResponse'
          description: ''
  /api/users/:
    get:
      operationId: users_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - users
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
    post:
      operationId: users_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/:
    get:
      operationId: users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    ChatRequest:
      type: object
      description: Defines the expected input structure for the chat API.
      properties:
        prompt:
          type: string
          description: The user's new message to the model.
          maxLength: 2000
        history:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: The full conversation history as a list of Content dictionaries.
        context_text:
          type: string
          nullable: true
          description: Optional context (e.g., RAG snippets) to augment the prompt.
          maxLength: 5000
        system_instructions:
          type: string
          nullable: true
          description: Optional instructions to guide the model's persona.
          maxLength: 1000
        model_name:
          type: string
          default: gemini-2.5-flash
          description: The Gemini model to use for generation.
          maxLength: 50
      required:
      - prompt
    ChatResponse:
      type: object
      description: Defines the expected output structure from the chat API.
      properties:
        response:
          type: string
          description: The model's generated text response.
        history:
          type: array
          items:
            type: object
            additionalProperties: {}
          description: The full, updated conversation history (including the latest
            turn).
      required:
      - history
      - response
    Counter:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        value:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - id
    Message:
      type: object
      properties:
        message:
          type: string
      required:
      - message
    MockResponse:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        response:
          type: string
      required:
      - id
      - response
    PaginatedMockResponseList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/MockResponse'
    PaginatedUserList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PatchedMockResponse:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        response:
          type: string
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        is_active:
          type: boolean
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        is_staff:
          type: boolean
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        is_active:
          type: boolean
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        is_staff:
          type: boolean
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
      required:
      - created
      - email
      - id
      - modified
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
