// This file is auto-generated by @hey-api/openapi-ts

/**
 * Defines the expected input structure for the chat API.
 */
export type ChatRequest = {
  /**
   * The user's new message to the model.
   */
  prompt: string;
  /**
   * The full conversation history as a list of Content dictionaries.
   */
  history?: Array<{
    [key: string]: unknown;
  }>;
  /**
   * Optional context (e.g., RAG snippets) to augment the prompt.
   */
  context_text?: string | null;
  /**
   * Optional instructions to guide the model's persona.
   */
  system_instructions?: string | null;
  /**
   * The Gemini model to use for generation.
   */
  model_name?: string;
};

/**
 * Defines the expected output structure from the chat API.
 */
export type ChatResponse = {
  /**
   * The model's generated text response.
   */
  response: string;
  /**
   * The full, updated conversation history (including the latest turn).
   */
  history: Array<{
    [key: string]: unknown;
  }>;
};

export type Checklist = {
  readonly id: number;
  result: string;
};

export type Counter = {
  readonly id: number;
  value?: number;
};

export type Message = {
  message: string;
};

export type MockResponse = {
  readonly id: number;
  response: string;
};

export type PaginatedChecklistList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<Checklist>;
};

export type PaginatedMockResponseList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<MockResponse>;
};

export type PaginatedUserList = {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: Array<User>;
};

export type PatchedChecklist = {
  readonly id?: number;
  result?: string;
};

export type PatchedMockResponse = {
  readonly id?: number;
  response?: string;
};

export type PatchedUser = {
  readonly id?: number;
  email?: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created?: string;
  readonly modified?: string;
  last_login?: string | null;
};

export type User = {
  readonly id: number;
  email: string;
  /**
   * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
   */
  is_active?: boolean;
  /**
   * Designates whether the user can log into this admin site.
   */
  is_staff?: boolean;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   */
  is_superuser?: boolean;
  readonly created: string;
  readonly modified: string;
  last_login?: string | null;
};

export type ChatChatCreateData = {
  requestBody: ChatRequest;
};

export type ChatChatCreateResponse = ChatResponse;

export type ChecklistListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type ChecklistListResponse = PaginatedChecklistList;

export type ChecklistCreateData = {
  requestBody: Checklist;
};

export type ChecklistCreateResponse = Checklist;

export type ChecklistRetrieveData = {
  /**
   * A unique integer value identifying this checklist result.
   */
  id: number;
};

export type ChecklistRetrieveResponse = Checklist;

export type ChecklistUpdateData = {
  /**
   * A unique integer value identifying this checklist result.
   */
  id: number;
  requestBody: Checklist;
};

export type ChecklistUpdateResponse = Checklist;

export type ChecklistPartialUpdateData = {
  /**
   * A unique integer value identifying this checklist result.
   */
  id: number;
  requestBody?: PatchedChecklist;
};

export type ChecklistPartialUpdateResponse = Checklist;

export type ChecklistDestroyData = {
  /**
   * A unique integer value identifying this checklist result.
   */
  id: number;
};

export type ChecklistDestroyResponse = void;

export type ChecklistJsonToStringCreateData = {
  requestBody: Checklist;
};

export type ChecklistJsonToStringCreateResponse = Checklist;

export type CounterIncrementCreateData = {
  requestBody?: Counter;
};

export type CounterIncrementCreateResponse = Counter;

export type InternalStatusListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type InternalStatusListResponse = unknown;

export type InternalStatusCreateResponse = unknown;

export type InternalStatusRetrieveData = {
  /**
   * A unique integer value identifying this internal status.
   */
  id: number;
};

export type InternalStatusRetrieveResponse = unknown;

export type InternalStatusUpdateData = {
  /**
   * A unique integer value identifying this internal status.
   */
  id: number;
};

export type InternalStatusUpdateResponse = unknown;

export type InternalStatusPartialUpdateData = {
  /**
   * A unique integer value identifying this internal status.
   */
  id: number;
};

export type InternalStatusPartialUpdateResponse = unknown;

export type InternalStatusDestroyData = {
  /**
   * A unique integer value identifying this internal status.
   */
  id: number;
};

export type InternalStatusDestroyResponse = void;

export type InternalStatusSetSystemInstructionCreateResponse = unknown;

export type RestRestCheckRetrieveResponse = Message;

export type TestResponseListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type TestResponseListResponse = PaginatedMockResponseList;

export type TestResponseCreateData = {
  requestBody: MockResponse;
};

export type TestResponseCreateResponse = MockResponse;

export type TestResponseRetrieveData = {
  /**
   * A unique integer value identifying this mock response.
   */
  id: number;
};

export type TestResponseRetrieveResponse = MockResponse;

export type TestResponseUpdateData = {
  /**
   * A unique integer value identifying this mock response.
   */
  id: number;
  requestBody: MockResponse;
};

export type TestResponseUpdateResponse = MockResponse;

export type TestResponsePartialUpdateData = {
  /**
   * A unique integer value identifying this mock response.
   */
  id: number;
  requestBody?: PatchedMockResponse;
};

export type TestResponsePartialUpdateResponse = MockResponse;

export type TestResponseDestroyData = {
  /**
   * A unique integer value identifying this mock response.
   */
  id: number;
};

export type TestResponseDestroyResponse = void;

export type TestResponseFetchByKeywordCreateData = {
  requestBody: MockResponse;
};

export type TestResponseFetchByKeywordCreateResponse = MockResponse;

export type UsersListData = {
  /**
   * Number of results to return per page.
   */
  limit?: number;
  /**
   * The initial index from which to return the results.
   */
  offset?: number;
};

export type UsersListResponse = PaginatedUserList;

export type UsersCreateData = {
  requestBody: User;
};

export type UsersCreateResponse = User;

export type UsersRetrieveData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type UsersRetrieveResponse = User;

export type UsersUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody: User;
};

export type UsersUpdateResponse = User;

export type UsersPartialUpdateData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
  requestBody?: PatchedUser;
};

export type UsersPartialUpdateResponse = User;

export type UsersDestroyData = {
  /**
   * A unique integer value identifying this user.
   */
  id: number;
};

export type UsersDestroyResponse = void;

export type $OpenApiTs = {
  "/api/chat/chat/": {
    post: {
      req: ChatChatCreateData;
      res: {
        200: ChatResponse;
      };
    };
  };
  "/api/checklist/": {
    get: {
      req: ChecklistListData;
      res: {
        200: PaginatedChecklistList;
      };
    };
    post: {
      req: ChecklistCreateData;
      res: {
        201: Checklist;
      };
    };
  };
  "/api/checklist/{id}/": {
    get: {
      req: ChecklistRetrieveData;
      res: {
        200: Checklist;
      };
    };
    put: {
      req: ChecklistUpdateData;
      res: {
        200: Checklist;
      };
    };
    patch: {
      req: ChecklistPartialUpdateData;
      res: {
        200: Checklist;
      };
    };
    delete: {
      req: ChecklistDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/checklist/json_to_string/": {
    post: {
      req: ChecklistJsonToStringCreateData;
      res: {
        200: Checklist;
      };
    };
  };
  "/api/counter/increment/": {
    post: {
      req: CounterIncrementCreateData;
      res: {
        200: Counter;
      };
    };
  };
  "/api/internal-status/": {
    get: {
      req: InternalStatusListData;
      res: {
        /**
         * No response body
         */
        200: unknown;
      };
    };
    post: {
      res: {
        /**
         * No response body
         */
        201: unknown;
      };
    };
  };
  "/api/internal-status/{id}/": {
    get: {
      req: InternalStatusRetrieveData;
      res: {
        /**
         * No response body
         */
        200: unknown;
      };
    };
    put: {
      req: InternalStatusUpdateData;
      res: {
        /**
         * No response body
         */
        200: unknown;
      };
    };
    patch: {
      req: InternalStatusPartialUpdateData;
      res: {
        /**
         * No response body
         */
        200: unknown;
      };
    };
    delete: {
      req: InternalStatusDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/internal-status/set_system_instruction/": {
    post: {
      res: {
        /**
         * No response body
         */
        200: unknown;
      };
    };
  };
  "/api/rest/rest-check/": {
    get: {
      res: {
        200: Message;
      };
    };
  };
  "/api/test-response/": {
    get: {
      req: TestResponseListData;
      res: {
        200: PaginatedMockResponseList;
      };
    };
    post: {
      req: TestResponseCreateData;
      res: {
        201: MockResponse;
      };
    };
  };
  "/api/test-response/{id}/": {
    get: {
      req: TestResponseRetrieveData;
      res: {
        200: MockResponse;
      };
    };
    put: {
      req: TestResponseUpdateData;
      res: {
        200: MockResponse;
      };
    };
    patch: {
      req: TestResponsePartialUpdateData;
      res: {
        200: MockResponse;
      };
    };
    delete: {
      req: TestResponseDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
  "/api/test-response/fetch_by_keyword/": {
    post: {
      req: TestResponseFetchByKeywordCreateData;
      res: {
        200: MockResponse;
      };
    };
  };
  "/api/users/": {
    get: {
      req: UsersListData;
      res: {
        200: PaginatedUserList;
      };
    };
    post: {
      req: UsersCreateData;
      res: {
        201: User;
      };
    };
  };
  "/api/users/{id}/": {
    get: {
      req: UsersRetrieveData;
      res: {
        200: User;
      };
    };
    put: {
      req: UsersUpdateData;
      res: {
        200: User;
      };
    };
    patch: {
      req: UsersPartialUpdateData;
      res: {
        200: User;
      };
    };
    delete: {
      req: UsersDestroyData;
      res: {
        /**
         * No response body
         */
        204: void;
      };
    };
  };
};
