# Generated by Django 5.2.6 on 2025-10-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_mockresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("result", models.TextField()),
            ],
        ),
    ]
