# Generated by Django 5.2.6 on 2025-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_checklistresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_internal", models.BooleanField(default=False)),
            ],
        ),
    ]
