# Generated by Django 5.2.6 on 2025-11-10 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_internalstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChecklistResult",
        ),
        migrations.DeleteModel(
            name="Counter",
        ),
        migrations.DeleteModel(
            name="InternalStatus",
        ),
    ]
