name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Necessario per Black/isort/flake8 e per eseguire pre-commit
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Esegue TUTTI gli hook definiti in .pre-commit-config.yaml
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  # (Opzionale) Lint Node con script di progetto, se usi ESLint/Typecheck
  node-lint:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present



